
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `course` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model course
 * 
 */
export type courseModel = runtime.Types.Result.DefaultSelection<Prisma.$coursePayload>

export type AggregateCourse = {
  _count: CourseCountAggregateOutputType | null
  _avg: CourseAvgAggregateOutputType | null
  _sum: CourseSumAggregateOutputType | null
  _min: CourseMinAggregateOutputType | null
  _max: CourseMaxAggregateOutputType | null
}

export type CourseAvgAggregateOutputType = {
  id: number | null
  duration: number | null
  price: number | null
}

export type CourseSumAggregateOutputType = {
  id: number | null
  duration: number | null
  price: number | null
}

export type CourseMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  duration: number | null
  price: number | null
  dateStart: Date | null
  dateEnd: Date | null
  img: string | null
}

export type CourseMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  duration: number | null
  price: number | null
  dateStart: Date | null
  dateEnd: Date | null
  img: string | null
}

export type CourseCountAggregateOutputType = {
  id: number
  name: number
  description: number
  duration: number
  price: number
  dateStart: number
  dateEnd: number
  img: number
  _all: number
}


export type CourseAvgAggregateInputType = {
  id?: true
  duration?: true
  price?: true
}

export type CourseSumAggregateInputType = {
  id?: true
  duration?: true
  price?: true
}

export type CourseMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  duration?: true
  price?: true
  dateStart?: true
  dateEnd?: true
  img?: true
}

export type CourseMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  duration?: true
  price?: true
  dateStart?: true
  dateEnd?: true
  img?: true
}

export type CourseCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  duration?: true
  price?: true
  dateStart?: true
  dateEnd?: true
  img?: true
  _all?: true
}

export type CourseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which course to aggregate.
   */
  where?: Prisma.courseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.courseOrderByWithRelationInput | Prisma.courseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.courseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned courses
  **/
  _count?: true | CourseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CourseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CourseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CourseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CourseMaxAggregateInputType
}

export type GetCourseAggregateType<T extends CourseAggregateArgs> = {
      [P in keyof T & keyof AggregateCourse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourse[P]>
    : Prisma.GetScalarType<T[P], AggregateCourse[P]>
}




export type courseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.courseWhereInput
  orderBy?: Prisma.courseOrderByWithAggregationInput | Prisma.courseOrderByWithAggregationInput[]
  by: Prisma.CourseScalarFieldEnum[] | Prisma.CourseScalarFieldEnum
  having?: Prisma.courseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CourseCountAggregateInputType | true
  _avg?: CourseAvgAggregateInputType
  _sum?: CourseSumAggregateInputType
  _min?: CourseMinAggregateInputType
  _max?: CourseMaxAggregateInputType
}

export type CourseGroupByOutputType = {
  id: number
  name: string
  description: string
  duration: number
  price: number
  dateStart: Date
  dateEnd: Date
  img: string
  _count: CourseCountAggregateOutputType | null
  _avg: CourseAvgAggregateOutputType | null
  _sum: CourseSumAggregateOutputType | null
  _min: CourseMinAggregateOutputType | null
  _max: CourseMaxAggregateOutputType | null
}

type GetCourseGroupByPayload<T extends courseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CourseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CourseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CourseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CourseGroupByOutputType[P]>
      }
    >
  >



export type courseWhereInput = {
  AND?: Prisma.courseWhereInput | Prisma.courseWhereInput[]
  OR?: Prisma.courseWhereInput[]
  NOT?: Prisma.courseWhereInput | Prisma.courseWhereInput[]
  id?: Prisma.IntFilter<"course"> | number
  name?: Prisma.StringFilter<"course"> | string
  description?: Prisma.StringFilter<"course"> | string
  duration?: Prisma.IntFilter<"course"> | number
  price?: Prisma.IntFilter<"course"> | number
  dateStart?: Prisma.DateTimeFilter<"course"> | Date | string
  dateEnd?: Prisma.DateTimeFilter<"course"> | Date | string
  img?: Prisma.StringFilter<"course"> | string
  lessons?: Prisma.LessonListRelationFilter
  coursesUser?: Prisma.CoursesUserListRelationFilter
  orderPay?: Prisma.OrderPayListRelationFilter
}

export type courseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
  dateStart?: Prisma.SortOrder
  dateEnd?: Prisma.SortOrder
  img?: Prisma.SortOrder
  lessons?: Prisma.lessonOrderByRelationAggregateInput
  coursesUser?: Prisma.coursesUserOrderByRelationAggregateInput
  orderPay?: Prisma.orderPayOrderByRelationAggregateInput
  _relevance?: Prisma.courseOrderByRelevanceInput
}

export type courseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.courseWhereInput | Prisma.courseWhereInput[]
  OR?: Prisma.courseWhereInput[]
  NOT?: Prisma.courseWhereInput | Prisma.courseWhereInput[]
  name?: Prisma.StringFilter<"course"> | string
  description?: Prisma.StringFilter<"course"> | string
  duration?: Prisma.IntFilter<"course"> | number
  price?: Prisma.IntFilter<"course"> | number
  dateStart?: Prisma.DateTimeFilter<"course"> | Date | string
  dateEnd?: Prisma.DateTimeFilter<"course"> | Date | string
  img?: Prisma.StringFilter<"course"> | string
  lessons?: Prisma.LessonListRelationFilter
  coursesUser?: Prisma.CoursesUserListRelationFilter
  orderPay?: Prisma.OrderPayListRelationFilter
}, "id">

export type courseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
  dateStart?: Prisma.SortOrder
  dateEnd?: Prisma.SortOrder
  img?: Prisma.SortOrder
  _count?: Prisma.courseCountOrderByAggregateInput
  _avg?: Prisma.courseAvgOrderByAggregateInput
  _max?: Prisma.courseMaxOrderByAggregateInput
  _min?: Prisma.courseMinOrderByAggregateInput
  _sum?: Prisma.courseSumOrderByAggregateInput
}

export type courseScalarWhereWithAggregatesInput = {
  AND?: Prisma.courseScalarWhereWithAggregatesInput | Prisma.courseScalarWhereWithAggregatesInput[]
  OR?: Prisma.courseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.courseScalarWhereWithAggregatesInput | Prisma.courseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"course"> | number
  name?: Prisma.StringWithAggregatesFilter<"course"> | string
  description?: Prisma.StringWithAggregatesFilter<"course"> | string
  duration?: Prisma.IntWithAggregatesFilter<"course"> | number
  price?: Prisma.IntWithAggregatesFilter<"course"> | number
  dateStart?: Prisma.DateTimeWithAggregatesFilter<"course"> | Date | string
  dateEnd?: Prisma.DateTimeWithAggregatesFilter<"course"> | Date | string
  img?: Prisma.StringWithAggregatesFilter<"course"> | string
}

export type courseCreateInput = {
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonCreateNestedManyWithoutCourseInput
  coursesUser?: Prisma.coursesUserCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayCreateNestedManyWithoutCourseInput
}

export type courseUncheckedCreateInput = {
  id?: number
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonUncheckedCreateNestedManyWithoutCourseInput
  coursesUser?: Prisma.coursesUserUncheckedCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayUncheckedCreateNestedManyWithoutCourseInput
}

export type courseUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUpdateManyWithoutCourseNestedInput
  coursesUser?: Prisma.coursesUserUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUpdateManyWithoutCourseNestedInput
}

export type courseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUncheckedUpdateManyWithoutCourseNestedInput
  coursesUser?: Prisma.coursesUserUncheckedUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUncheckedUpdateManyWithoutCourseNestedInput
}

export type courseCreateManyInput = {
  id?: number
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
}

export type courseUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
}

export type courseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
}

export type courseOrderByRelevanceInput = {
  fields: Prisma.courseOrderByRelevanceFieldEnum | Prisma.courseOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type courseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
  dateStart?: Prisma.SortOrder
  dateEnd?: Prisma.SortOrder
  img?: Prisma.SortOrder
}

export type courseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type courseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
  dateStart?: Prisma.SortOrder
  dateEnd?: Prisma.SortOrder
  img?: Prisma.SortOrder
}

export type courseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
  dateStart?: Prisma.SortOrder
  dateEnd?: Prisma.SortOrder
  img?: Prisma.SortOrder
}

export type courseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type CourseScalarRelationFilter = {
  is?: Prisma.courseWhereInput
  isNot?: Prisma.courseWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type courseCreateNestedOneWithoutCoursesUserInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutCoursesUserInput, Prisma.courseUncheckedCreateWithoutCoursesUserInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutCoursesUserInput
  connect?: Prisma.courseWhereUniqueInput
}

export type courseUpdateOneRequiredWithoutCoursesUserNestedInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutCoursesUserInput, Prisma.courseUncheckedCreateWithoutCoursesUserInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutCoursesUserInput
  upsert?: Prisma.courseUpsertWithoutCoursesUserInput
  connect?: Prisma.courseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.courseUpdateToOneWithWhereWithoutCoursesUserInput, Prisma.courseUpdateWithoutCoursesUserInput>, Prisma.courseUncheckedUpdateWithoutCoursesUserInput>
}

export type courseCreateNestedOneWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutLessonsInput, Prisma.courseUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutLessonsInput
  connect?: Prisma.courseWhereUniqueInput
}

export type courseUpdateOneRequiredWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutLessonsInput, Prisma.courseUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutLessonsInput
  upsert?: Prisma.courseUpsertWithoutLessonsInput
  connect?: Prisma.courseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.courseUpdateToOneWithWhereWithoutLessonsInput, Prisma.courseUpdateWithoutLessonsInput>, Prisma.courseUncheckedUpdateWithoutLessonsInput>
}

export type courseCreateNestedOneWithoutOrderPayInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutOrderPayInput, Prisma.courseUncheckedCreateWithoutOrderPayInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutOrderPayInput
  connect?: Prisma.courseWhereUniqueInput
}

export type courseUpdateOneRequiredWithoutOrderPayNestedInput = {
  create?: Prisma.XOR<Prisma.courseCreateWithoutOrderPayInput, Prisma.courseUncheckedCreateWithoutOrderPayInput>
  connectOrCreate?: Prisma.courseCreateOrConnectWithoutOrderPayInput
  upsert?: Prisma.courseUpsertWithoutOrderPayInput
  connect?: Prisma.courseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.courseUpdateToOneWithWhereWithoutOrderPayInput, Prisma.courseUpdateWithoutOrderPayInput>, Prisma.courseUncheckedUpdateWithoutOrderPayInput>
}

export type courseCreateWithoutCoursesUserInput = {
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayCreateNestedManyWithoutCourseInput
}

export type courseUncheckedCreateWithoutCoursesUserInput = {
  id?: number
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonUncheckedCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayUncheckedCreateNestedManyWithoutCourseInput
}

export type courseCreateOrConnectWithoutCoursesUserInput = {
  where: Prisma.courseWhereUniqueInput
  create: Prisma.XOR<Prisma.courseCreateWithoutCoursesUserInput, Prisma.courseUncheckedCreateWithoutCoursesUserInput>
}

export type courseUpsertWithoutCoursesUserInput = {
  update: Prisma.XOR<Prisma.courseUpdateWithoutCoursesUserInput, Prisma.courseUncheckedUpdateWithoutCoursesUserInput>
  create: Prisma.XOR<Prisma.courseCreateWithoutCoursesUserInput, Prisma.courseUncheckedCreateWithoutCoursesUserInput>
  where?: Prisma.courseWhereInput
}

export type courseUpdateToOneWithWhereWithoutCoursesUserInput = {
  where?: Prisma.courseWhereInput
  data: Prisma.XOR<Prisma.courseUpdateWithoutCoursesUserInput, Prisma.courseUncheckedUpdateWithoutCoursesUserInput>
}

export type courseUpdateWithoutCoursesUserInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUpdateManyWithoutCourseNestedInput
}

export type courseUncheckedUpdateWithoutCoursesUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUncheckedUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUncheckedUpdateManyWithoutCourseNestedInput
}

export type courseCreateWithoutLessonsInput = {
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  coursesUser?: Prisma.coursesUserCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayCreateNestedManyWithoutCourseInput
}

export type courseUncheckedCreateWithoutLessonsInput = {
  id?: number
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  coursesUser?: Prisma.coursesUserUncheckedCreateNestedManyWithoutCourseInput
  orderPay?: Prisma.orderPayUncheckedCreateNestedManyWithoutCourseInput
}

export type courseCreateOrConnectWithoutLessonsInput = {
  where: Prisma.courseWhereUniqueInput
  create: Prisma.XOR<Prisma.courseCreateWithoutLessonsInput, Prisma.courseUncheckedCreateWithoutLessonsInput>
}

export type courseUpsertWithoutLessonsInput = {
  update: Prisma.XOR<Prisma.courseUpdateWithoutLessonsInput, Prisma.courseUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.courseCreateWithoutLessonsInput, Prisma.courseUncheckedCreateWithoutLessonsInput>
  where?: Prisma.courseWhereInput
}

export type courseUpdateToOneWithWhereWithoutLessonsInput = {
  where?: Prisma.courseWhereInput
  data: Prisma.XOR<Prisma.courseUpdateWithoutLessonsInput, Prisma.courseUncheckedUpdateWithoutLessonsInput>
}

export type courseUpdateWithoutLessonsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  coursesUser?: Prisma.coursesUserUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUpdateManyWithoutCourseNestedInput
}

export type courseUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  coursesUser?: Prisma.coursesUserUncheckedUpdateManyWithoutCourseNestedInput
  orderPay?: Prisma.orderPayUncheckedUpdateManyWithoutCourseNestedInput
}

export type courseCreateWithoutOrderPayInput = {
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonCreateNestedManyWithoutCourseInput
  coursesUser?: Prisma.coursesUserCreateNestedManyWithoutCourseInput
}

export type courseUncheckedCreateWithoutOrderPayInput = {
  id?: number
  name: string
  description: string
  duration: number
  price: number
  dateStart?: Date | string
  dateEnd: Date | string
  img: string
  lessons?: Prisma.lessonUncheckedCreateNestedManyWithoutCourseInput
  coursesUser?: Prisma.coursesUserUncheckedCreateNestedManyWithoutCourseInput
}

export type courseCreateOrConnectWithoutOrderPayInput = {
  where: Prisma.courseWhereUniqueInput
  create: Prisma.XOR<Prisma.courseCreateWithoutOrderPayInput, Prisma.courseUncheckedCreateWithoutOrderPayInput>
}

export type courseUpsertWithoutOrderPayInput = {
  update: Prisma.XOR<Prisma.courseUpdateWithoutOrderPayInput, Prisma.courseUncheckedUpdateWithoutOrderPayInput>
  create: Prisma.XOR<Prisma.courseCreateWithoutOrderPayInput, Prisma.courseUncheckedCreateWithoutOrderPayInput>
  where?: Prisma.courseWhereInput
}

export type courseUpdateToOneWithWhereWithoutOrderPayInput = {
  where?: Prisma.courseWhereInput
  data: Prisma.XOR<Prisma.courseUpdateWithoutOrderPayInput, Prisma.courseUncheckedUpdateWithoutOrderPayInput>
}

export type courseUpdateWithoutOrderPayInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUpdateManyWithoutCourseNestedInput
  coursesUser?: Prisma.coursesUserUpdateManyWithoutCourseNestedInput
}

export type courseUncheckedUpdateWithoutOrderPayInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  dateStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dateEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  img?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonUncheckedUpdateManyWithoutCourseNestedInput
  coursesUser?: Prisma.coursesUserUncheckedUpdateManyWithoutCourseNestedInput
}


/**
 * Count Type CourseCountOutputType
 */

export type CourseCountOutputType = {
  lessons: number
  coursesUser: number
  orderPay: number
}

export type CourseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | CourseCountOutputTypeCountLessonsArgs
  coursesUser?: boolean | CourseCountOutputTypeCountCoursesUserArgs
  orderPay?: boolean | CourseCountOutputTypeCountOrderPayArgs
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseCountOutputType
   */
  select?: Prisma.CourseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountLessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.lessonWhereInput
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountCoursesUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.coursesUserWhereInput
}

/**
 * CourseCountOutputType without action
 */
export type CourseCountOutputTypeCountOrderPayArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orderPayWhereInput
}


export type courseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  duration?: boolean
  price?: boolean
  dateStart?: boolean
  dateEnd?: boolean
  img?: boolean
  lessons?: boolean | Prisma.course$lessonsArgs<ExtArgs>
  coursesUser?: boolean | Prisma.course$coursesUserArgs<ExtArgs>
  orderPay?: boolean | Prisma.course$orderPayArgs<ExtArgs>
  _count?: boolean | Prisma.CourseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["course"]>



export type courseSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  duration?: boolean
  price?: boolean
  dateStart?: boolean
  dateEnd?: boolean
  img?: boolean
}

export type courseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "duration" | "price" | "dateStart" | "dateEnd" | "img", ExtArgs["result"]["course"]>
export type courseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.course$lessonsArgs<ExtArgs>
  coursesUser?: boolean | Prisma.course$coursesUserArgs<ExtArgs>
  orderPay?: boolean | Prisma.course$orderPayArgs<ExtArgs>
  _count?: boolean | Prisma.CourseCountOutputTypeDefaultArgs<ExtArgs>
}

export type $coursePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "course"
  objects: {
    lessons: Prisma.$lessonPayload<ExtArgs>[]
    coursesUser: Prisma.$coursesUserPayload<ExtArgs>[]
    orderPay: Prisma.$orderPayPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string
    duration: number
    price: number
    dateStart: Date
    dateEnd: Date
    img: string
  }, ExtArgs["result"]["course"]>
  composites: {}
}

export type courseGetPayload<S extends boolean | null | undefined | courseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$coursePayload, S>

export type courseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<courseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CourseCountAggregateInputType | true
  }

export interface courseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['course'], meta: { name: 'course' } }
  /**
   * Find zero or one Course that matches the filter.
   * @param {courseFindUniqueArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends courseFindUniqueArgs>(args: Prisma.SelectSubset<T, courseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Course that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {courseFindUniqueOrThrowArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends courseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, courseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Course that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseFindFirstArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends courseFindFirstArgs>(args?: Prisma.SelectSubset<T, courseFindFirstArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Course that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseFindFirstOrThrowArgs} args - Arguments to find a Course
   * @example
   * // Get one Course
   * const course = await prisma.course.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends courseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, courseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Courses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Courses
   * const courses = await prisma.course.findMany()
   * 
   * // Get first 10 Courses
   * const courses = await prisma.course.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const courseWithIdOnly = await prisma.course.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends courseFindManyArgs>(args?: Prisma.SelectSubset<T, courseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Course.
   * @param {courseCreateArgs} args - Arguments to create a Course.
   * @example
   * // Create one Course
   * const Course = await prisma.course.create({
   *   data: {
   *     // ... data to create a Course
   *   }
   * })
   * 
   */
  create<T extends courseCreateArgs>(args: Prisma.SelectSubset<T, courseCreateArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Courses.
   * @param {courseCreateManyArgs} args - Arguments to create many Courses.
   * @example
   * // Create many Courses
   * const course = await prisma.course.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends courseCreateManyArgs>(args?: Prisma.SelectSubset<T, courseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Course.
   * @param {courseDeleteArgs} args - Arguments to delete one Course.
   * @example
   * // Delete one Course
   * const Course = await prisma.course.delete({
   *   where: {
   *     // ... filter to delete one Course
   *   }
   * })
   * 
   */
  delete<T extends courseDeleteArgs>(args: Prisma.SelectSubset<T, courseDeleteArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Course.
   * @param {courseUpdateArgs} args - Arguments to update one Course.
   * @example
   * // Update one Course
   * const course = await prisma.course.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends courseUpdateArgs>(args: Prisma.SelectSubset<T, courseUpdateArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Courses.
   * @param {courseDeleteManyArgs} args - Arguments to filter Courses to delete.
   * @example
   * // Delete a few Courses
   * const { count } = await prisma.course.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends courseDeleteManyArgs>(args?: Prisma.SelectSubset<T, courseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Courses
   * const course = await prisma.course.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends courseUpdateManyArgs>(args: Prisma.SelectSubset<T, courseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Course.
   * @param {courseUpsertArgs} args - Arguments to update or create a Course.
   * @example
   * // Update or create a Course
   * const course = await prisma.course.upsert({
   *   create: {
   *     // ... data to create a Course
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Course we want to update
   *   }
   * })
   */
  upsert<T extends courseUpsertArgs>(args: Prisma.SelectSubset<T, courseUpsertArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseCountArgs} args - Arguments to filter Courses to count.
   * @example
   * // Count the number of Courses
   * const count = await prisma.course.count({
   *   where: {
   *     // ... the filter for the Courses we want to count
   *   }
   * })
  **/
  count<T extends courseCountArgs>(
    args?: Prisma.Subset<T, courseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CourseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Course.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CourseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CourseAggregateArgs>(args: Prisma.Subset<T, CourseAggregateArgs>): Prisma.PrismaPromise<GetCourseAggregateType<T>>

  /**
   * Group by Course.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {courseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends courseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: courseGroupByArgs['orderBy'] }
      : { orderBy?: courseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, courseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCourseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the course model
 */
readonly fields: courseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for course.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__courseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.course$lessonsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.course$lessonsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  coursesUser<T extends Prisma.course$coursesUserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.course$coursesUserArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orderPay<T extends Prisma.course$orderPayArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.course$orderPayArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the course model
 */
export interface courseFieldRefs {
  readonly id: Prisma.FieldRef<"course", 'Int'>
  readonly name: Prisma.FieldRef<"course", 'String'>
  readonly description: Prisma.FieldRef<"course", 'String'>
  readonly duration: Prisma.FieldRef<"course", 'Int'>
  readonly price: Prisma.FieldRef<"course", 'Int'>
  readonly dateStart: Prisma.FieldRef<"course", 'DateTime'>
  readonly dateEnd: Prisma.FieldRef<"course", 'DateTime'>
  readonly img: Prisma.FieldRef<"course", 'String'>
}
    

// Custom InputTypes
/**
 * course findUnique
 */
export type courseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter, which course to fetch.
   */
  where: Prisma.courseWhereUniqueInput
}

/**
 * course findUniqueOrThrow
 */
export type courseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter, which course to fetch.
   */
  where: Prisma.courseWhereUniqueInput
}

/**
 * course findFirst
 */
export type courseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter, which course to fetch.
   */
  where?: Prisma.courseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.courseOrderByWithRelationInput | Prisma.courseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for courses.
   */
  cursor?: Prisma.courseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of courses.
   */
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * course findFirstOrThrow
 */
export type courseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter, which course to fetch.
   */
  where?: Prisma.courseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.courseOrderByWithRelationInput | Prisma.courseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for courses.
   */
  cursor?: Prisma.courseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of courses.
   */
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * course findMany
 */
export type courseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where?: Prisma.courseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.courseOrderByWithRelationInput | Prisma.courseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing courses.
   */
  cursor?: Prisma.courseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  distinct?: Prisma.CourseScalarFieldEnum | Prisma.CourseScalarFieldEnum[]
}

/**
 * course create
 */
export type courseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * The data needed to create a course.
   */
  data: Prisma.XOR<Prisma.courseCreateInput, Prisma.courseUncheckedCreateInput>
}

/**
 * course createMany
 */
export type courseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many courses.
   */
  data: Prisma.courseCreateManyInput | Prisma.courseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * course update
 */
export type courseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * The data needed to update a course.
   */
  data: Prisma.XOR<Prisma.courseUpdateInput, Prisma.courseUncheckedUpdateInput>
  /**
   * Choose, which course to update.
   */
  where: Prisma.courseWhereUniqueInput
}

/**
 * course updateMany
 */
export type courseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update courses.
   */
  data: Prisma.XOR<Prisma.courseUpdateManyMutationInput, Prisma.courseUncheckedUpdateManyInput>
  /**
   * Filter which courses to update
   */
  where?: Prisma.courseWhereInput
  /**
   * Limit how many courses to update.
   */
  limit?: number
}

/**
 * course upsert
 */
export type courseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * The filter to search for the course to update in case it exists.
   */
  where: Prisma.courseWhereUniqueInput
  /**
   * In case the course found by the `where` argument doesn't exist, create a new course with this data.
   */
  create: Prisma.XOR<Prisma.courseCreateInput, Prisma.courseUncheckedCreateInput>
  /**
   * In case the course was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.courseUpdateInput, Prisma.courseUncheckedUpdateInput>
}

/**
 * course delete
 */
export type courseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
  /**
   * Filter which course to delete.
   */
  where: Prisma.courseWhereUniqueInput
}

/**
 * course deleteMany
 */
export type courseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which courses to delete
   */
  where?: Prisma.courseWhereInput
  /**
   * Limit how many courses to delete.
   */
  limit?: number
}

/**
 * course.lessons
 */
export type course$lessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  where?: Prisma.lessonWhereInput
  orderBy?: Prisma.lessonOrderByWithRelationInput | Prisma.lessonOrderByWithRelationInput[]
  cursor?: Prisma.lessonWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * course.coursesUser
 */
export type course$coursesUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  where?: Prisma.coursesUserWhereInput
  orderBy?: Prisma.coursesUserOrderByWithRelationInput | Prisma.coursesUserOrderByWithRelationInput[]
  cursor?: Prisma.coursesUserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CoursesUserScalarFieldEnum | Prisma.CoursesUserScalarFieldEnum[]
}

/**
 * course.orderPay
 */
export type course$orderPayArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  where?: Prisma.orderPayWhereInput
  orderBy?: Prisma.orderPayOrderByWithRelationInput | Prisma.orderPayOrderByWithRelationInput[]
  cursor?: Prisma.orderPayWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderPayScalarFieldEnum | Prisma.OrderPayScalarFieldEnum[]
}

/**
 * course without action
 */
export type courseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the course
   */
  select?: Prisma.courseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the course
   */
  omit?: Prisma.courseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.courseInclude<ExtArgs> | null
}
