
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `coursesUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model coursesUser
 * 
 */
export type coursesUserModel = runtime.Types.Result.DefaultSelection<Prisma.$coursesUserPayload>

export type AggregateCoursesUser = {
  _count: CoursesUserCountAggregateOutputType | null
  _avg: CoursesUserAvgAggregateOutputType | null
  _sum: CoursesUserSumAggregateOutputType | null
  _min: CoursesUserMinAggregateOutputType | null
  _max: CoursesUserMaxAggregateOutputType | null
}

export type CoursesUserAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type CoursesUserSumAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type CoursesUserMinAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type CoursesUserMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type CoursesUserCountAggregateOutputType = {
  id: number
  userId: number
  courseId: number
  _all: number
}


export type CoursesUserAvgAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type CoursesUserSumAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type CoursesUserMinAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type CoursesUserMaxAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type CoursesUserCountAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  _all?: true
}

export type CoursesUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which coursesUser to aggregate.
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coursesUsers to fetch.
   */
  orderBy?: Prisma.coursesUserOrderByWithRelationInput | Prisma.coursesUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.coursesUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coursesUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coursesUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned coursesUsers
  **/
  _count?: true | CoursesUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CoursesUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CoursesUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CoursesUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CoursesUserMaxAggregateInputType
}

export type GetCoursesUserAggregateType<T extends CoursesUserAggregateArgs> = {
      [P in keyof T & keyof AggregateCoursesUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCoursesUser[P]>
    : Prisma.GetScalarType<T[P], AggregateCoursesUser[P]>
}




export type coursesUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.coursesUserWhereInput
  orderBy?: Prisma.coursesUserOrderByWithAggregationInput | Prisma.coursesUserOrderByWithAggregationInput[]
  by: Prisma.CoursesUserScalarFieldEnum[] | Prisma.CoursesUserScalarFieldEnum
  having?: Prisma.coursesUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CoursesUserCountAggregateInputType | true
  _avg?: CoursesUserAvgAggregateInputType
  _sum?: CoursesUserSumAggregateInputType
  _min?: CoursesUserMinAggregateInputType
  _max?: CoursesUserMaxAggregateInputType
}

export type CoursesUserGroupByOutputType = {
  id: number
  userId: number
  courseId: number
  _count: CoursesUserCountAggregateOutputType | null
  _avg: CoursesUserAvgAggregateOutputType | null
  _sum: CoursesUserSumAggregateOutputType | null
  _min: CoursesUserMinAggregateOutputType | null
  _max: CoursesUserMaxAggregateOutputType | null
}

type GetCoursesUserGroupByPayload<T extends coursesUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CoursesUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CoursesUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CoursesUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CoursesUserGroupByOutputType[P]>
      }
    >
  >



export type coursesUserWhereInput = {
  AND?: Prisma.coursesUserWhereInput | Prisma.coursesUserWhereInput[]
  OR?: Prisma.coursesUserWhereInput[]
  NOT?: Prisma.coursesUserWhereInput | Prisma.coursesUserWhereInput[]
  id?: Prisma.IntFilter<"coursesUser"> | number
  userId?: Prisma.IntFilter<"coursesUser"> | number
  courseId?: Prisma.IntFilter<"coursesUser"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}

export type coursesUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  user?: Prisma.userOrderByWithRelationInput
  course?: Prisma.courseOrderByWithRelationInput
}

export type coursesUserWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.coursesUserWhereInput | Prisma.coursesUserWhereInput[]
  OR?: Prisma.coursesUserWhereInput[]
  NOT?: Prisma.coursesUserWhereInput | Prisma.coursesUserWhereInput[]
  userId?: Prisma.IntFilter<"coursesUser"> | number
  courseId?: Prisma.IntFilter<"coursesUser"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}, "id">

export type coursesUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  _count?: Prisma.coursesUserCountOrderByAggregateInput
  _avg?: Prisma.coursesUserAvgOrderByAggregateInput
  _max?: Prisma.coursesUserMaxOrderByAggregateInput
  _min?: Prisma.coursesUserMinOrderByAggregateInput
  _sum?: Prisma.coursesUserSumOrderByAggregateInput
}

export type coursesUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.coursesUserScalarWhereWithAggregatesInput | Prisma.coursesUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.coursesUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.coursesUserScalarWhereWithAggregatesInput | Prisma.coursesUserScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"coursesUser"> | number
  userId?: Prisma.IntWithAggregatesFilter<"coursesUser"> | number
  courseId?: Prisma.IntWithAggregatesFilter<"coursesUser"> | number
}

export type coursesUserCreateInput = {
  user: Prisma.userCreateNestedOneWithoutCoursesUserInput
  course: Prisma.courseCreateNestedOneWithoutCoursesUserInput
}

export type coursesUserUncheckedCreateInput = {
  id?: number
  userId: number
  courseId: number
}

export type coursesUserUpdateInput = {
  user?: Prisma.userUpdateOneRequiredWithoutCoursesUserNestedInput
  course?: Prisma.courseUpdateOneRequiredWithoutCoursesUserNestedInput
}

export type coursesUserUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type coursesUserCreateManyInput = {
  id?: number
  userId: number
  courseId: number
}

export type coursesUserUpdateManyMutationInput = {

}

export type coursesUserUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CoursesUserListRelationFilter = {
  every?: Prisma.coursesUserWhereInput
  some?: Prisma.coursesUserWhereInput
  none?: Prisma.coursesUserWhereInput
}

export type coursesUserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type coursesUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type coursesUserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type coursesUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type coursesUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type coursesUserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type coursesUserCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput> | Prisma.coursesUserCreateWithoutCourseInput[] | Prisma.coursesUserUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutCourseInput | Prisma.coursesUserCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.coursesUserCreateManyCourseInputEnvelope
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
}

export type coursesUserUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput> | Prisma.coursesUserCreateWithoutCourseInput[] | Prisma.coursesUserUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutCourseInput | Prisma.coursesUserCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.coursesUserCreateManyCourseInputEnvelope
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
}

export type coursesUserUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput> | Prisma.coursesUserCreateWithoutCourseInput[] | Prisma.coursesUserUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutCourseInput | Prisma.coursesUserCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.coursesUserUpsertWithWhereUniqueWithoutCourseInput | Prisma.coursesUserUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.coursesUserCreateManyCourseInputEnvelope
  set?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  disconnect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  delete?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  update?: Prisma.coursesUserUpdateWithWhereUniqueWithoutCourseInput | Prisma.coursesUserUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.coursesUserUpdateManyWithWhereWithoutCourseInput | Prisma.coursesUserUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
}

export type coursesUserUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput> | Prisma.coursesUserCreateWithoutCourseInput[] | Prisma.coursesUserUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutCourseInput | Prisma.coursesUserCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.coursesUserUpsertWithWhereUniqueWithoutCourseInput | Prisma.coursesUserUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.coursesUserCreateManyCourseInputEnvelope
  set?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  disconnect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  delete?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  update?: Prisma.coursesUserUpdateWithWhereUniqueWithoutCourseInput | Prisma.coursesUserUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.coursesUserUpdateManyWithWhereWithoutCourseInput | Prisma.coursesUserUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
}

export type coursesUserCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput> | Prisma.coursesUserCreateWithoutUserInput[] | Prisma.coursesUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutUserInput | Prisma.coursesUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.coursesUserCreateManyUserInputEnvelope
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
}

export type coursesUserUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput> | Prisma.coursesUserCreateWithoutUserInput[] | Prisma.coursesUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutUserInput | Prisma.coursesUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.coursesUserCreateManyUserInputEnvelope
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
}

export type coursesUserUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput> | Prisma.coursesUserCreateWithoutUserInput[] | Prisma.coursesUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutUserInput | Prisma.coursesUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.coursesUserUpsertWithWhereUniqueWithoutUserInput | Prisma.coursesUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.coursesUserCreateManyUserInputEnvelope
  set?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  disconnect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  delete?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  update?: Prisma.coursesUserUpdateWithWhereUniqueWithoutUserInput | Prisma.coursesUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.coursesUserUpdateManyWithWhereWithoutUserInput | Prisma.coursesUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
}

export type coursesUserUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput> | Prisma.coursesUserCreateWithoutUserInput[] | Prisma.coursesUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.coursesUserCreateOrConnectWithoutUserInput | Prisma.coursesUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.coursesUserUpsertWithWhereUniqueWithoutUserInput | Prisma.coursesUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.coursesUserCreateManyUserInputEnvelope
  set?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  disconnect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  delete?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  connect?: Prisma.coursesUserWhereUniqueInput | Prisma.coursesUserWhereUniqueInput[]
  update?: Prisma.coursesUserUpdateWithWhereUniqueWithoutUserInput | Prisma.coursesUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.coursesUserUpdateManyWithWhereWithoutUserInput | Prisma.coursesUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
}

export type coursesUserCreateWithoutCourseInput = {
  user: Prisma.userCreateNestedOneWithoutCoursesUserInput
}

export type coursesUserUncheckedCreateWithoutCourseInput = {
  id?: number
  userId: number
}

export type coursesUserCreateOrConnectWithoutCourseInput = {
  where: Prisma.coursesUserWhereUniqueInput
  create: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput>
}

export type coursesUserCreateManyCourseInputEnvelope = {
  data: Prisma.coursesUserCreateManyCourseInput | Prisma.coursesUserCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type coursesUserUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.coursesUserWhereUniqueInput
  update: Prisma.XOR<Prisma.coursesUserUpdateWithoutCourseInput, Prisma.coursesUserUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.coursesUserCreateWithoutCourseInput, Prisma.coursesUserUncheckedCreateWithoutCourseInput>
}

export type coursesUserUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.coursesUserWhereUniqueInput
  data: Prisma.XOR<Prisma.coursesUserUpdateWithoutCourseInput, Prisma.coursesUserUncheckedUpdateWithoutCourseInput>
}

export type coursesUserUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.coursesUserScalarWhereInput
  data: Prisma.XOR<Prisma.coursesUserUpdateManyMutationInput, Prisma.coursesUserUncheckedUpdateManyWithoutCourseInput>
}

export type coursesUserScalarWhereInput = {
  AND?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
  OR?: Prisma.coursesUserScalarWhereInput[]
  NOT?: Prisma.coursesUserScalarWhereInput | Prisma.coursesUserScalarWhereInput[]
  id?: Prisma.IntFilter<"coursesUser"> | number
  userId?: Prisma.IntFilter<"coursesUser"> | number
  courseId?: Prisma.IntFilter<"coursesUser"> | number
}

export type coursesUserCreateWithoutUserInput = {
  course: Prisma.courseCreateNestedOneWithoutCoursesUserInput
}

export type coursesUserUncheckedCreateWithoutUserInput = {
  id?: number
  courseId: number
}

export type coursesUserCreateOrConnectWithoutUserInput = {
  where: Prisma.coursesUserWhereUniqueInput
  create: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput>
}

export type coursesUserCreateManyUserInputEnvelope = {
  data: Prisma.coursesUserCreateManyUserInput | Prisma.coursesUserCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type coursesUserUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.coursesUserWhereUniqueInput
  update: Prisma.XOR<Prisma.coursesUserUpdateWithoutUserInput, Prisma.coursesUserUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.coursesUserCreateWithoutUserInput, Prisma.coursesUserUncheckedCreateWithoutUserInput>
}

export type coursesUserUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.coursesUserWhereUniqueInput
  data: Prisma.XOR<Prisma.coursesUserUpdateWithoutUserInput, Prisma.coursesUserUncheckedUpdateWithoutUserInput>
}

export type coursesUserUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.coursesUserScalarWhereInput
  data: Prisma.XOR<Prisma.coursesUserUpdateManyMutationInput, Prisma.coursesUserUncheckedUpdateManyWithoutUserInput>
}

export type coursesUserCreateManyCourseInput = {
  id?: number
  userId: number
}

export type coursesUserUpdateWithoutCourseInput = {
  user?: Prisma.userUpdateOneRequiredWithoutCoursesUserNestedInput
}

export type coursesUserUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type coursesUserUncheckedUpdateManyWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type coursesUserCreateManyUserInput = {
  id?: number
  courseId: number
}

export type coursesUserUpdateWithoutUserInput = {
  course?: Prisma.courseUpdateOneRequiredWithoutCoursesUserNestedInput
}

export type coursesUserUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type coursesUserUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type coursesUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["coursesUser"]>



export type coursesUserSelectScalar = {
  id?: boolean
  userId?: boolean
  courseId?: boolean
}

export type coursesUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "courseId", ExtArgs["result"]["coursesUser"]>
export type coursesUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}

export type $coursesUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "coursesUser"
  objects: {
    user: Prisma.$userPayload<ExtArgs>
    course: Prisma.$coursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    courseId: number
  }, ExtArgs["result"]["coursesUser"]>
  composites: {}
}

export type coursesUserGetPayload<S extends boolean | null | undefined | coursesUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$coursesUserPayload, S>

export type coursesUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<coursesUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CoursesUserCountAggregateInputType | true
  }

export interface coursesUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['coursesUser'], meta: { name: 'coursesUser' } }
  /**
   * Find zero or one CoursesUser that matches the filter.
   * @param {coursesUserFindUniqueArgs} args - Arguments to find a CoursesUser
   * @example
   * // Get one CoursesUser
   * const coursesUser = await prisma.coursesUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends coursesUserFindUniqueArgs>(args: Prisma.SelectSubset<T, coursesUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CoursesUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {coursesUserFindUniqueOrThrowArgs} args - Arguments to find a CoursesUser
   * @example
   * // Get one CoursesUser
   * const coursesUser = await prisma.coursesUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends coursesUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, coursesUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CoursesUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserFindFirstArgs} args - Arguments to find a CoursesUser
   * @example
   * // Get one CoursesUser
   * const coursesUser = await prisma.coursesUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends coursesUserFindFirstArgs>(args?: Prisma.SelectSubset<T, coursesUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CoursesUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserFindFirstOrThrowArgs} args - Arguments to find a CoursesUser
   * @example
   * // Get one CoursesUser
   * const coursesUser = await prisma.coursesUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends coursesUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, coursesUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CoursesUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CoursesUsers
   * const coursesUsers = await prisma.coursesUser.findMany()
   * 
   * // Get first 10 CoursesUsers
   * const coursesUsers = await prisma.coursesUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const coursesUserWithIdOnly = await prisma.coursesUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends coursesUserFindManyArgs>(args?: Prisma.SelectSubset<T, coursesUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CoursesUser.
   * @param {coursesUserCreateArgs} args - Arguments to create a CoursesUser.
   * @example
   * // Create one CoursesUser
   * const CoursesUser = await prisma.coursesUser.create({
   *   data: {
   *     // ... data to create a CoursesUser
   *   }
   * })
   * 
   */
  create<T extends coursesUserCreateArgs>(args: Prisma.SelectSubset<T, coursesUserCreateArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CoursesUsers.
   * @param {coursesUserCreateManyArgs} args - Arguments to create many CoursesUsers.
   * @example
   * // Create many CoursesUsers
   * const coursesUser = await prisma.coursesUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends coursesUserCreateManyArgs>(args?: Prisma.SelectSubset<T, coursesUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CoursesUser.
   * @param {coursesUserDeleteArgs} args - Arguments to delete one CoursesUser.
   * @example
   * // Delete one CoursesUser
   * const CoursesUser = await prisma.coursesUser.delete({
   *   where: {
   *     // ... filter to delete one CoursesUser
   *   }
   * })
   * 
   */
  delete<T extends coursesUserDeleteArgs>(args: Prisma.SelectSubset<T, coursesUserDeleteArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CoursesUser.
   * @param {coursesUserUpdateArgs} args - Arguments to update one CoursesUser.
   * @example
   * // Update one CoursesUser
   * const coursesUser = await prisma.coursesUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends coursesUserUpdateArgs>(args: Prisma.SelectSubset<T, coursesUserUpdateArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CoursesUsers.
   * @param {coursesUserDeleteManyArgs} args - Arguments to filter CoursesUsers to delete.
   * @example
   * // Delete a few CoursesUsers
   * const { count } = await prisma.coursesUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends coursesUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, coursesUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CoursesUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CoursesUsers
   * const coursesUser = await prisma.coursesUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends coursesUserUpdateManyArgs>(args: Prisma.SelectSubset<T, coursesUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CoursesUser.
   * @param {coursesUserUpsertArgs} args - Arguments to update or create a CoursesUser.
   * @example
   * // Update or create a CoursesUser
   * const coursesUser = await prisma.coursesUser.upsert({
   *   create: {
   *     // ... data to create a CoursesUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CoursesUser we want to update
   *   }
   * })
   */
  upsert<T extends coursesUserUpsertArgs>(args: Prisma.SelectSubset<T, coursesUserUpsertArgs<ExtArgs>>): Prisma.Prisma__coursesUserClient<runtime.Types.Result.GetResult<Prisma.$coursesUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CoursesUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserCountArgs} args - Arguments to filter CoursesUsers to count.
   * @example
   * // Count the number of CoursesUsers
   * const count = await prisma.coursesUser.count({
   *   where: {
   *     // ... the filter for the CoursesUsers we want to count
   *   }
   * })
  **/
  count<T extends coursesUserCountArgs>(
    args?: Prisma.Subset<T, coursesUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CoursesUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CoursesUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoursesUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CoursesUserAggregateArgs>(args: Prisma.Subset<T, CoursesUserAggregateArgs>): Prisma.PrismaPromise<GetCoursesUserAggregateType<T>>

  /**
   * Group by CoursesUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends coursesUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: coursesUserGroupByArgs['orderBy'] }
      : { orderBy?: coursesUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, coursesUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCoursesUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the coursesUser model
 */
readonly fields: coursesUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for coursesUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__coursesUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  course<T extends Prisma.courseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.courseDefaultArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the coursesUser model
 */
export interface coursesUserFieldRefs {
  readonly id: Prisma.FieldRef<"coursesUser", 'Int'>
  readonly userId: Prisma.FieldRef<"coursesUser", 'Int'>
  readonly courseId: Prisma.FieldRef<"coursesUser", 'Int'>
}
    

// Custom InputTypes
/**
 * coursesUser findUnique
 */
export type coursesUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter, which coursesUser to fetch.
   */
  where: Prisma.coursesUserWhereUniqueInput
}

/**
 * coursesUser findUniqueOrThrow
 */
export type coursesUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter, which coursesUser to fetch.
   */
  where: Prisma.coursesUserWhereUniqueInput
}

/**
 * coursesUser findFirst
 */
export type coursesUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter, which coursesUser to fetch.
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coursesUsers to fetch.
   */
  orderBy?: Prisma.coursesUserOrderByWithRelationInput | Prisma.coursesUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for coursesUsers.
   */
  cursor?: Prisma.coursesUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coursesUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coursesUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of coursesUsers.
   */
  distinct?: Prisma.CoursesUserScalarFieldEnum | Prisma.CoursesUserScalarFieldEnum[]
}

/**
 * coursesUser findFirstOrThrow
 */
export type coursesUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter, which coursesUser to fetch.
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coursesUsers to fetch.
   */
  orderBy?: Prisma.coursesUserOrderByWithRelationInput | Prisma.coursesUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for coursesUsers.
   */
  cursor?: Prisma.coursesUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coursesUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coursesUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of coursesUsers.
   */
  distinct?: Prisma.CoursesUserScalarFieldEnum | Prisma.CoursesUserScalarFieldEnum[]
}

/**
 * coursesUser findMany
 */
export type coursesUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter, which coursesUsers to fetch.
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of coursesUsers to fetch.
   */
  orderBy?: Prisma.coursesUserOrderByWithRelationInput | Prisma.coursesUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing coursesUsers.
   */
  cursor?: Prisma.coursesUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` coursesUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` coursesUsers.
   */
  skip?: number
  distinct?: Prisma.CoursesUserScalarFieldEnum | Prisma.CoursesUserScalarFieldEnum[]
}

/**
 * coursesUser create
 */
export type coursesUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * The data needed to create a coursesUser.
   */
  data: Prisma.XOR<Prisma.coursesUserCreateInput, Prisma.coursesUserUncheckedCreateInput>
}

/**
 * coursesUser createMany
 */
export type coursesUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many coursesUsers.
   */
  data: Prisma.coursesUserCreateManyInput | Prisma.coursesUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * coursesUser update
 */
export type coursesUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * The data needed to update a coursesUser.
   */
  data: Prisma.XOR<Prisma.coursesUserUpdateInput, Prisma.coursesUserUncheckedUpdateInput>
  /**
   * Choose, which coursesUser to update.
   */
  where: Prisma.coursesUserWhereUniqueInput
}

/**
 * coursesUser updateMany
 */
export type coursesUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update coursesUsers.
   */
  data: Prisma.XOR<Prisma.coursesUserUpdateManyMutationInput, Prisma.coursesUserUncheckedUpdateManyInput>
  /**
   * Filter which coursesUsers to update
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * Limit how many coursesUsers to update.
   */
  limit?: number
}

/**
 * coursesUser upsert
 */
export type coursesUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * The filter to search for the coursesUser to update in case it exists.
   */
  where: Prisma.coursesUserWhereUniqueInput
  /**
   * In case the coursesUser found by the `where` argument doesn't exist, create a new coursesUser with this data.
   */
  create: Prisma.XOR<Prisma.coursesUserCreateInput, Prisma.coursesUserUncheckedCreateInput>
  /**
   * In case the coursesUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.coursesUserUpdateInput, Prisma.coursesUserUncheckedUpdateInput>
}

/**
 * coursesUser delete
 */
export type coursesUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
  /**
   * Filter which coursesUser to delete.
   */
  where: Prisma.coursesUserWhereUniqueInput
}

/**
 * coursesUser deleteMany
 */
export type coursesUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which coursesUsers to delete
   */
  where?: Prisma.coursesUserWhereInput
  /**
   * Limit how many coursesUsers to delete.
   */
  limit?: number
}

/**
 * coursesUser without action
 */
export type coursesUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the coursesUser
   */
  select?: Prisma.coursesUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the coursesUser
   */
  omit?: Prisma.coursesUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesUserInclude<ExtArgs> | null
}
