
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `lesson` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model lesson
 * 
 */
export type lessonModel = runtime.Types.Result.DefaultSelection<Prisma.$lessonPayload>

export type AggregateLesson = {
  _count: LessonCountAggregateOutputType | null
  _avg: LessonAvgAggregateOutputType | null
  _sum: LessonSumAggregateOutputType | null
  _min: LessonMinAggregateOutputType | null
  _max: LessonMaxAggregateOutputType | null
}

export type LessonAvgAggregateOutputType = {
  id: number | null
  coursesId: number | null
  duration: number | null
}

export type LessonSumAggregateOutputType = {
  id: number | null
  coursesId: number | null
  duration: number | null
}

export type LessonMinAggregateOutputType = {
  id: number | null
  coursesId: number | null
  title: string | null
  text: string | null
  supertube_url: string | null
  duration: number | null
}

export type LessonMaxAggregateOutputType = {
  id: number | null
  coursesId: number | null
  title: string | null
  text: string | null
  supertube_url: string | null
  duration: number | null
}

export type LessonCountAggregateOutputType = {
  id: number
  coursesId: number
  title: number
  text: number
  supertube_url: number
  duration: number
  _all: number
}


export type LessonAvgAggregateInputType = {
  id?: true
  coursesId?: true
  duration?: true
}

export type LessonSumAggregateInputType = {
  id?: true
  coursesId?: true
  duration?: true
}

export type LessonMinAggregateInputType = {
  id?: true
  coursesId?: true
  title?: true
  text?: true
  supertube_url?: true
  duration?: true
}

export type LessonMaxAggregateInputType = {
  id?: true
  coursesId?: true
  title?: true
  text?: true
  supertube_url?: true
  duration?: true
}

export type LessonCountAggregateInputType = {
  id?: true
  coursesId?: true
  title?: true
  text?: true
  supertube_url?: true
  duration?: true
  _all?: true
}

export type LessonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which lesson to aggregate.
   */
  where?: Prisma.lessonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lessons to fetch.
   */
  orderBy?: Prisma.lessonOrderByWithRelationInput | Prisma.lessonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.lessonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lessons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lessons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned lessons
  **/
  _count?: true | LessonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LessonAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LessonSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LessonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LessonMaxAggregateInputType
}

export type GetLessonAggregateType<T extends LessonAggregateArgs> = {
      [P in keyof T & keyof AggregateLesson]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLesson[P]>
    : Prisma.GetScalarType<T[P], AggregateLesson[P]>
}




export type lessonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.lessonWhereInput
  orderBy?: Prisma.lessonOrderByWithAggregationInput | Prisma.lessonOrderByWithAggregationInput[]
  by: Prisma.LessonScalarFieldEnum[] | Prisma.LessonScalarFieldEnum
  having?: Prisma.lessonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LessonCountAggregateInputType | true
  _avg?: LessonAvgAggregateInputType
  _sum?: LessonSumAggregateInputType
  _min?: LessonMinAggregateInputType
  _max?: LessonMaxAggregateInputType
}

export type LessonGroupByOutputType = {
  id: number
  coursesId: number
  title: string
  text: string
  supertube_url: string | null
  duration: number
  _count: LessonCountAggregateOutputType | null
  _avg: LessonAvgAggregateOutputType | null
  _sum: LessonSumAggregateOutputType | null
  _min: LessonMinAggregateOutputType | null
  _max: LessonMaxAggregateOutputType | null
}

type GetLessonGroupByPayload<T extends lessonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LessonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LessonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LessonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LessonGroupByOutputType[P]>
      }
    >
  >



export type lessonWhereInput = {
  AND?: Prisma.lessonWhereInput | Prisma.lessonWhereInput[]
  OR?: Prisma.lessonWhereInput[]
  NOT?: Prisma.lessonWhereInput | Prisma.lessonWhereInput[]
  id?: Prisma.IntFilter<"lesson"> | number
  coursesId?: Prisma.IntFilter<"lesson"> | number
  title?: Prisma.StringFilter<"lesson"> | string
  text?: Prisma.StringFilter<"lesson"> | string
  supertube_url?: Prisma.StringNullableFilter<"lesson"> | string | null
  duration?: Prisma.IntFilter<"lesson"> | number
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}

export type lessonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  text?: Prisma.SortOrder
  supertube_url?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrder
  course?: Prisma.courseOrderByWithRelationInput
  _relevance?: Prisma.lessonOrderByRelevanceInput
}

export type lessonWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.lessonWhereInput | Prisma.lessonWhereInput[]
  OR?: Prisma.lessonWhereInput[]
  NOT?: Prisma.lessonWhereInput | Prisma.lessonWhereInput[]
  coursesId?: Prisma.IntFilter<"lesson"> | number
  title?: Prisma.StringFilter<"lesson"> | string
  text?: Prisma.StringFilter<"lesson"> | string
  supertube_url?: Prisma.StringNullableFilter<"lesson"> | string | null
  duration?: Prisma.IntFilter<"lesson"> | number
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}, "id">

export type lessonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  text?: Prisma.SortOrder
  supertube_url?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrder
  _count?: Prisma.lessonCountOrderByAggregateInput
  _avg?: Prisma.lessonAvgOrderByAggregateInput
  _max?: Prisma.lessonMaxOrderByAggregateInput
  _min?: Prisma.lessonMinOrderByAggregateInput
  _sum?: Prisma.lessonSumOrderByAggregateInput
}

export type lessonScalarWhereWithAggregatesInput = {
  AND?: Prisma.lessonScalarWhereWithAggregatesInput | Prisma.lessonScalarWhereWithAggregatesInput[]
  OR?: Prisma.lessonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.lessonScalarWhereWithAggregatesInput | Prisma.lessonScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"lesson"> | number
  coursesId?: Prisma.IntWithAggregatesFilter<"lesson"> | number
  title?: Prisma.StringWithAggregatesFilter<"lesson"> | string
  text?: Prisma.StringWithAggregatesFilter<"lesson"> | string
  supertube_url?: Prisma.StringNullableWithAggregatesFilter<"lesson"> | string | null
  duration?: Prisma.IntWithAggregatesFilter<"lesson"> | number
}

export type lessonCreateInput = {
  title: string
  text: string
  supertube_url?: string | null
  duration: number
  course: Prisma.courseCreateNestedOneWithoutLessonsInput
}

export type lessonUncheckedCreateInput = {
  id?: number
  coursesId: number
  title: string
  text: string
  supertube_url?: string | null
  duration: number
}

export type lessonUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  course?: Prisma.courseUpdateOneRequiredWithoutLessonsNestedInput
}

export type lessonUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  coursesId?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type lessonCreateManyInput = {
  id?: number
  coursesId: number
  title: string
  text: string
  supertube_url?: string | null
  duration: number
}

export type lessonUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type lessonUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  coursesId?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LessonListRelationFilter = {
  every?: Prisma.lessonWhereInput
  some?: Prisma.lessonWhereInput
  none?: Prisma.lessonWhereInput
}

export type lessonOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type lessonOrderByRelevanceInput = {
  fields: Prisma.lessonOrderByRelevanceFieldEnum | Prisma.lessonOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type lessonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  text?: Prisma.SortOrder
  supertube_url?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type lessonAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type lessonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  text?: Prisma.SortOrder
  supertube_url?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type lessonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  text?: Prisma.SortOrder
  supertube_url?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type lessonSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  coursesId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type lessonCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput> | Prisma.lessonCreateWithoutCourseInput[] | Prisma.lessonUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.lessonCreateOrConnectWithoutCourseInput | Prisma.lessonCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.lessonCreateManyCourseInputEnvelope
  connect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
}

export type lessonUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput> | Prisma.lessonCreateWithoutCourseInput[] | Prisma.lessonUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.lessonCreateOrConnectWithoutCourseInput | Prisma.lessonCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.lessonCreateManyCourseInputEnvelope
  connect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
}

export type lessonUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput> | Prisma.lessonCreateWithoutCourseInput[] | Prisma.lessonUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.lessonCreateOrConnectWithoutCourseInput | Prisma.lessonCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.lessonUpsertWithWhereUniqueWithoutCourseInput | Prisma.lessonUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.lessonCreateManyCourseInputEnvelope
  set?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  disconnect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  delete?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  connect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  update?: Prisma.lessonUpdateWithWhereUniqueWithoutCourseInput | Prisma.lessonUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.lessonUpdateManyWithWhereWithoutCourseInput | Prisma.lessonUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.lessonScalarWhereInput | Prisma.lessonScalarWhereInput[]
}

export type lessonUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput> | Prisma.lessonCreateWithoutCourseInput[] | Prisma.lessonUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.lessonCreateOrConnectWithoutCourseInput | Prisma.lessonCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.lessonUpsertWithWhereUniqueWithoutCourseInput | Prisma.lessonUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.lessonCreateManyCourseInputEnvelope
  set?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  disconnect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  delete?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  connect?: Prisma.lessonWhereUniqueInput | Prisma.lessonWhereUniqueInput[]
  update?: Prisma.lessonUpdateWithWhereUniqueWithoutCourseInput | Prisma.lessonUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.lessonUpdateManyWithWhereWithoutCourseInput | Prisma.lessonUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.lessonScalarWhereInput | Prisma.lessonScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type lessonCreateWithoutCourseInput = {
  title: string
  text: string
  supertube_url?: string | null
  duration: number
}

export type lessonUncheckedCreateWithoutCourseInput = {
  id?: number
  title: string
  text: string
  supertube_url?: string | null
  duration: number
}

export type lessonCreateOrConnectWithoutCourseInput = {
  where: Prisma.lessonWhereUniqueInput
  create: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput>
}

export type lessonCreateManyCourseInputEnvelope = {
  data: Prisma.lessonCreateManyCourseInput | Prisma.lessonCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type lessonUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.lessonWhereUniqueInput
  update: Prisma.XOR<Prisma.lessonUpdateWithoutCourseInput, Prisma.lessonUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.lessonCreateWithoutCourseInput, Prisma.lessonUncheckedCreateWithoutCourseInput>
}

export type lessonUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.lessonWhereUniqueInput
  data: Prisma.XOR<Prisma.lessonUpdateWithoutCourseInput, Prisma.lessonUncheckedUpdateWithoutCourseInput>
}

export type lessonUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.lessonScalarWhereInput
  data: Prisma.XOR<Prisma.lessonUpdateManyMutationInput, Prisma.lessonUncheckedUpdateManyWithoutCourseInput>
}

export type lessonScalarWhereInput = {
  AND?: Prisma.lessonScalarWhereInput | Prisma.lessonScalarWhereInput[]
  OR?: Prisma.lessonScalarWhereInput[]
  NOT?: Prisma.lessonScalarWhereInput | Prisma.lessonScalarWhereInput[]
  id?: Prisma.IntFilter<"lesson"> | number
  coursesId?: Prisma.IntFilter<"lesson"> | number
  title?: Prisma.StringFilter<"lesson"> | string
  text?: Prisma.StringFilter<"lesson"> | string
  supertube_url?: Prisma.StringNullableFilter<"lesson"> | string | null
  duration?: Prisma.IntFilter<"lesson"> | number
}

export type lessonCreateManyCourseInput = {
  id?: number
  title: string
  text: string
  supertube_url?: string | null
  duration: number
}

export type lessonUpdateWithoutCourseInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type lessonUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type lessonUncheckedUpdateManyWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  supertube_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}



export type lessonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  coursesId?: boolean
  title?: boolean
  text?: boolean
  supertube_url?: boolean
  duration?: boolean
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lesson"]>



export type lessonSelectScalar = {
  id?: boolean
  coursesId?: boolean
  title?: boolean
  text?: boolean
  supertube_url?: boolean
  duration?: boolean
}

export type lessonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "coursesId" | "title" | "text" | "supertube_url" | "duration", ExtArgs["result"]["lesson"]>
export type lessonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}

export type $lessonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "lesson"
  objects: {
    course: Prisma.$coursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    coursesId: number
    title: string
    text: string
    supertube_url: string | null
    duration: number
  }, ExtArgs["result"]["lesson"]>
  composites: {}
}

export type lessonGetPayload<S extends boolean | null | undefined | lessonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$lessonPayload, S>

export type lessonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<lessonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LessonCountAggregateInputType | true
  }

export interface lessonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['lesson'], meta: { name: 'lesson' } }
  /**
   * Find zero or one Lesson that matches the filter.
   * @param {lessonFindUniqueArgs} args - Arguments to find a Lesson
   * @example
   * // Get one Lesson
   * const lesson = await prisma.lesson.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends lessonFindUniqueArgs>(args: Prisma.SelectSubset<T, lessonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lesson that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {lessonFindUniqueOrThrowArgs} args - Arguments to find a Lesson
   * @example
   * // Get one Lesson
   * const lesson = await prisma.lesson.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends lessonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, lessonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lesson that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonFindFirstArgs} args - Arguments to find a Lesson
   * @example
   * // Get one Lesson
   * const lesson = await prisma.lesson.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends lessonFindFirstArgs>(args?: Prisma.SelectSubset<T, lessonFindFirstArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lesson that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonFindFirstOrThrowArgs} args - Arguments to find a Lesson
   * @example
   * // Get one Lesson
   * const lesson = await prisma.lesson.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends lessonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, lessonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Lessons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Lessons
   * const lessons = await prisma.lesson.findMany()
   * 
   * // Get first 10 Lessons
   * const lessons = await prisma.lesson.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lessonWithIdOnly = await prisma.lesson.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends lessonFindManyArgs>(args?: Prisma.SelectSubset<T, lessonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lesson.
   * @param {lessonCreateArgs} args - Arguments to create a Lesson.
   * @example
   * // Create one Lesson
   * const Lesson = await prisma.lesson.create({
   *   data: {
   *     // ... data to create a Lesson
   *   }
   * })
   * 
   */
  create<T extends lessonCreateArgs>(args: Prisma.SelectSubset<T, lessonCreateArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Lessons.
   * @param {lessonCreateManyArgs} args - Arguments to create many Lessons.
   * @example
   * // Create many Lessons
   * const lesson = await prisma.lesson.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends lessonCreateManyArgs>(args?: Prisma.SelectSubset<T, lessonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Lesson.
   * @param {lessonDeleteArgs} args - Arguments to delete one Lesson.
   * @example
   * // Delete one Lesson
   * const Lesson = await prisma.lesson.delete({
   *   where: {
   *     // ... filter to delete one Lesson
   *   }
   * })
   * 
   */
  delete<T extends lessonDeleteArgs>(args: Prisma.SelectSubset<T, lessonDeleteArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lesson.
   * @param {lessonUpdateArgs} args - Arguments to update one Lesson.
   * @example
   * // Update one Lesson
   * const lesson = await prisma.lesson.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends lessonUpdateArgs>(args: Prisma.SelectSubset<T, lessonUpdateArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Lessons.
   * @param {lessonDeleteManyArgs} args - Arguments to filter Lessons to delete.
   * @example
   * // Delete a few Lessons
   * const { count } = await prisma.lesson.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends lessonDeleteManyArgs>(args?: Prisma.SelectSubset<T, lessonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lessons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Lessons
   * const lesson = await prisma.lesson.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends lessonUpdateManyArgs>(args: Prisma.SelectSubset<T, lessonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Lesson.
   * @param {lessonUpsertArgs} args - Arguments to update or create a Lesson.
   * @example
   * // Update or create a Lesson
   * const lesson = await prisma.lesson.upsert({
   *   create: {
   *     // ... data to create a Lesson
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lesson we want to update
   *   }
   * })
   */
  upsert<T extends lessonUpsertArgs>(args: Prisma.SelectSubset<T, lessonUpsertArgs<ExtArgs>>): Prisma.Prisma__lessonClient<runtime.Types.Result.GetResult<Prisma.$lessonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Lessons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonCountArgs} args - Arguments to filter Lessons to count.
   * @example
   * // Count the number of Lessons
   * const count = await prisma.lesson.count({
   *   where: {
   *     // ... the filter for the Lessons we want to count
   *   }
   * })
  **/
  count<T extends lessonCountArgs>(
    args?: Prisma.Subset<T, lessonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LessonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lesson.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LessonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LessonAggregateArgs>(args: Prisma.Subset<T, LessonAggregateArgs>): Prisma.PrismaPromise<GetLessonAggregateType<T>>

  /**
   * Group by Lesson.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lessonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends lessonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: lessonGroupByArgs['orderBy'] }
      : { orderBy?: lessonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, lessonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLessonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the lesson model
 */
readonly fields: lessonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for lesson.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__lessonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  course<T extends Prisma.courseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.courseDefaultArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the lesson model
 */
export interface lessonFieldRefs {
  readonly id: Prisma.FieldRef<"lesson", 'Int'>
  readonly coursesId: Prisma.FieldRef<"lesson", 'Int'>
  readonly title: Prisma.FieldRef<"lesson", 'String'>
  readonly text: Prisma.FieldRef<"lesson", 'String'>
  readonly supertube_url: Prisma.FieldRef<"lesson", 'String'>
  readonly duration: Prisma.FieldRef<"lesson", 'Int'>
}
    

// Custom InputTypes
/**
 * lesson findUnique
 */
export type lessonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter, which lesson to fetch.
   */
  where: Prisma.lessonWhereUniqueInput
}

/**
 * lesson findUniqueOrThrow
 */
export type lessonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter, which lesson to fetch.
   */
  where: Prisma.lessonWhereUniqueInput
}

/**
 * lesson findFirst
 */
export type lessonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter, which lesson to fetch.
   */
  where?: Prisma.lessonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lessons to fetch.
   */
  orderBy?: Prisma.lessonOrderByWithRelationInput | Prisma.lessonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for lessons.
   */
  cursor?: Prisma.lessonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lessons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lessons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of lessons.
   */
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * lesson findFirstOrThrow
 */
export type lessonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter, which lesson to fetch.
   */
  where?: Prisma.lessonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lessons to fetch.
   */
  orderBy?: Prisma.lessonOrderByWithRelationInput | Prisma.lessonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for lessons.
   */
  cursor?: Prisma.lessonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lessons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lessons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of lessons.
   */
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * lesson findMany
 */
export type lessonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter, which lessons to fetch.
   */
  where?: Prisma.lessonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lessons to fetch.
   */
  orderBy?: Prisma.lessonOrderByWithRelationInput | Prisma.lessonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing lessons.
   */
  cursor?: Prisma.lessonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lessons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lessons.
   */
  skip?: number
  distinct?: Prisma.LessonScalarFieldEnum | Prisma.LessonScalarFieldEnum[]
}

/**
 * lesson create
 */
export type lessonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * The data needed to create a lesson.
   */
  data: Prisma.XOR<Prisma.lessonCreateInput, Prisma.lessonUncheckedCreateInput>
}

/**
 * lesson createMany
 */
export type lessonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many lessons.
   */
  data: Prisma.lessonCreateManyInput | Prisma.lessonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * lesson update
 */
export type lessonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * The data needed to update a lesson.
   */
  data: Prisma.XOR<Prisma.lessonUpdateInput, Prisma.lessonUncheckedUpdateInput>
  /**
   * Choose, which lesson to update.
   */
  where: Prisma.lessonWhereUniqueInput
}

/**
 * lesson updateMany
 */
export type lessonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update lessons.
   */
  data: Prisma.XOR<Prisma.lessonUpdateManyMutationInput, Prisma.lessonUncheckedUpdateManyInput>
  /**
   * Filter which lessons to update
   */
  where?: Prisma.lessonWhereInput
  /**
   * Limit how many lessons to update.
   */
  limit?: number
}

/**
 * lesson upsert
 */
export type lessonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * The filter to search for the lesson to update in case it exists.
   */
  where: Prisma.lessonWhereUniqueInput
  /**
   * In case the lesson found by the `where` argument doesn't exist, create a new lesson with this data.
   */
  create: Prisma.XOR<Prisma.lessonCreateInput, Prisma.lessonUncheckedCreateInput>
  /**
   * In case the lesson was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.lessonUpdateInput, Prisma.lessonUncheckedUpdateInput>
}

/**
 * lesson delete
 */
export type lessonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
  /**
   * Filter which lesson to delete.
   */
  where: Prisma.lessonWhereUniqueInput
}

/**
 * lesson deleteMany
 */
export type lessonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which lessons to delete
   */
  where?: Prisma.lessonWhereInput
  /**
   * Limit how many lessons to delete.
   */
  limit?: number
}

/**
 * lesson without action
 */
export type lessonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lesson
   */
  select?: Prisma.lessonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lesson
   */
  omit?: Prisma.lessonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonInclude<ExtArgs> | null
}
