
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orderPay` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model orderPay
 * 
 */
export type orderPayModel = runtime.Types.Result.DefaultSelection<Prisma.$orderPayPayload>

export type AggregateOrderPay = {
  _count: OrderPayCountAggregateOutputType | null
  _avg: OrderPayAvgAggregateOutputType | null
  _sum: OrderPaySumAggregateOutputType | null
  _min: OrderPayMinAggregateOutputType | null
  _max: OrderPayMaxAggregateOutputType | null
}

export type OrderPayAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type OrderPaySumAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
}

export type OrderPayMinAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
  status_pay: $Enums.StatusPay | null
}

export type OrderPayMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  courseId: number | null
  status_pay: $Enums.StatusPay | null
}

export type OrderPayCountAggregateOutputType = {
  id: number
  userId: number
  courseId: number
  status_pay: number
  _all: number
}


export type OrderPayAvgAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type OrderPaySumAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
}

export type OrderPayMinAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  status_pay?: true
}

export type OrderPayMaxAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  status_pay?: true
}

export type OrderPayCountAggregateInputType = {
  id?: true
  userId?: true
  courseId?: true
  status_pay?: true
  _all?: true
}

export type OrderPayAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orderPay to aggregate.
   */
  where?: Prisma.orderPayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orderPays to fetch.
   */
  orderBy?: Prisma.orderPayOrderByWithRelationInput | Prisma.orderPayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.orderPayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orderPays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orderPays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orderPays
  **/
  _count?: true | OrderPayCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderPayAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderPaySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderPayMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderPayMaxAggregateInputType
}

export type GetOrderPayAggregateType<T extends OrderPayAggregateArgs> = {
      [P in keyof T & keyof AggregateOrderPay]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrderPay[P]>
    : Prisma.GetScalarType<T[P], AggregateOrderPay[P]>
}




export type orderPayGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.orderPayWhereInput
  orderBy?: Prisma.orderPayOrderByWithAggregationInput | Prisma.orderPayOrderByWithAggregationInput[]
  by: Prisma.OrderPayScalarFieldEnum[] | Prisma.OrderPayScalarFieldEnum
  having?: Prisma.orderPayScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderPayCountAggregateInputType | true
  _avg?: OrderPayAvgAggregateInputType
  _sum?: OrderPaySumAggregateInputType
  _min?: OrderPayMinAggregateInputType
  _max?: OrderPayMaxAggregateInputType
}

export type OrderPayGroupByOutputType = {
  id: number
  userId: number
  courseId: number
  status_pay: $Enums.StatusPay
  _count: OrderPayCountAggregateOutputType | null
  _avg: OrderPayAvgAggregateOutputType | null
  _sum: OrderPaySumAggregateOutputType | null
  _min: OrderPayMinAggregateOutputType | null
  _max: OrderPayMaxAggregateOutputType | null
}

type GetOrderPayGroupByPayload<T extends orderPayGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderPayGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderPayGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderPayGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderPayGroupByOutputType[P]>
      }
    >
  >



export type orderPayWhereInput = {
  AND?: Prisma.orderPayWhereInput | Prisma.orderPayWhereInput[]
  OR?: Prisma.orderPayWhereInput[]
  NOT?: Prisma.orderPayWhereInput | Prisma.orderPayWhereInput[]
  id?: Prisma.IntFilter<"orderPay"> | number
  userId?: Prisma.IntFilter<"orderPay"> | number
  courseId?: Prisma.IntFilter<"orderPay"> | number
  status_pay?: Prisma.EnumStatusPayFilter<"orderPay"> | $Enums.StatusPay
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}

export type orderPayOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  status_pay?: Prisma.SortOrder
  user?: Prisma.userOrderByWithRelationInput
  course?: Prisma.courseOrderByWithRelationInput
}

export type orderPayWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.orderPayWhereInput | Prisma.orderPayWhereInput[]
  OR?: Prisma.orderPayWhereInput[]
  NOT?: Prisma.orderPayWhereInput | Prisma.orderPayWhereInput[]
  userId?: Prisma.IntFilter<"orderPay"> | number
  courseId?: Prisma.IntFilter<"orderPay"> | number
  status_pay?: Prisma.EnumStatusPayFilter<"orderPay"> | $Enums.StatusPay
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.userWhereInput>
  course?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.courseWhereInput>
}, "id">

export type orderPayOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  status_pay?: Prisma.SortOrder
  _count?: Prisma.orderPayCountOrderByAggregateInput
  _avg?: Prisma.orderPayAvgOrderByAggregateInput
  _max?: Prisma.orderPayMaxOrderByAggregateInput
  _min?: Prisma.orderPayMinOrderByAggregateInput
  _sum?: Prisma.orderPaySumOrderByAggregateInput
}

export type orderPayScalarWhereWithAggregatesInput = {
  AND?: Prisma.orderPayScalarWhereWithAggregatesInput | Prisma.orderPayScalarWhereWithAggregatesInput[]
  OR?: Prisma.orderPayScalarWhereWithAggregatesInput[]
  NOT?: Prisma.orderPayScalarWhereWithAggregatesInput | Prisma.orderPayScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orderPay"> | number
  userId?: Prisma.IntWithAggregatesFilter<"orderPay"> | number
  courseId?: Prisma.IntWithAggregatesFilter<"orderPay"> | number
  status_pay?: Prisma.EnumStatusPayWithAggregatesFilter<"orderPay"> | $Enums.StatusPay
}

export type orderPayCreateInput = {
  status_pay: $Enums.StatusPay
  user: Prisma.userCreateNestedOneWithoutOrderPayInput
  course: Prisma.courseCreateNestedOneWithoutOrderPayInput
}

export type orderPayUncheckedCreateInput = {
  id?: number
  userId: number
  courseId: number
  status_pay: $Enums.StatusPay
}

export type orderPayUpdateInput = {
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
  user?: Prisma.userUpdateOneRequiredWithoutOrderPayNestedInput
  course?: Prisma.courseUpdateOneRequiredWithoutOrderPayNestedInput
}

export type orderPayUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type orderPayCreateManyInput = {
  id?: number
  userId: number
  courseId: number
  status_pay: $Enums.StatusPay
}

export type orderPayUpdateManyMutationInput = {
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type orderPayUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type OrderPayListRelationFilter = {
  every?: Prisma.orderPayWhereInput
  some?: Prisma.orderPayWhereInput
  none?: Prisma.orderPayWhereInput
}

export type orderPayOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type orderPayCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  status_pay?: Prisma.SortOrder
}

export type orderPayAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type orderPayMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  status_pay?: Prisma.SortOrder
}

export type orderPayMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
  status_pay?: Prisma.SortOrder
}

export type orderPaySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  courseId?: Prisma.SortOrder
}

export type orderPayCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput> | Prisma.orderPayCreateWithoutCourseInput[] | Prisma.orderPayUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutCourseInput | Prisma.orderPayCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.orderPayCreateManyCourseInputEnvelope
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
}

export type orderPayUncheckedCreateNestedManyWithoutCourseInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput> | Prisma.orderPayCreateWithoutCourseInput[] | Prisma.orderPayUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutCourseInput | Prisma.orderPayCreateOrConnectWithoutCourseInput[]
  createMany?: Prisma.orderPayCreateManyCourseInputEnvelope
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
}

export type orderPayUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput> | Prisma.orderPayCreateWithoutCourseInput[] | Prisma.orderPayUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutCourseInput | Prisma.orderPayCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.orderPayUpsertWithWhereUniqueWithoutCourseInput | Prisma.orderPayUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.orderPayCreateManyCourseInputEnvelope
  set?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  disconnect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  delete?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  update?: Prisma.orderPayUpdateWithWhereUniqueWithoutCourseInput | Prisma.orderPayUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.orderPayUpdateManyWithWhereWithoutCourseInput | Prisma.orderPayUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
}

export type orderPayUncheckedUpdateManyWithoutCourseNestedInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput> | Prisma.orderPayCreateWithoutCourseInput[] | Prisma.orderPayUncheckedCreateWithoutCourseInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutCourseInput | Prisma.orderPayCreateOrConnectWithoutCourseInput[]
  upsert?: Prisma.orderPayUpsertWithWhereUniqueWithoutCourseInput | Prisma.orderPayUpsertWithWhereUniqueWithoutCourseInput[]
  createMany?: Prisma.orderPayCreateManyCourseInputEnvelope
  set?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  disconnect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  delete?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  update?: Prisma.orderPayUpdateWithWhereUniqueWithoutCourseInput | Prisma.orderPayUpdateWithWhereUniqueWithoutCourseInput[]
  updateMany?: Prisma.orderPayUpdateManyWithWhereWithoutCourseInput | Prisma.orderPayUpdateManyWithWhereWithoutCourseInput[]
  deleteMany?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
}

export type EnumStatusPayFieldUpdateOperationsInput = {
  set?: $Enums.StatusPay
}

export type orderPayCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput> | Prisma.orderPayCreateWithoutUserInput[] | Prisma.orderPayUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutUserInput | Prisma.orderPayCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.orderPayCreateManyUserInputEnvelope
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
}

export type orderPayUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput> | Prisma.orderPayCreateWithoutUserInput[] | Prisma.orderPayUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutUserInput | Prisma.orderPayCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.orderPayCreateManyUserInputEnvelope
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
}

export type orderPayUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput> | Prisma.orderPayCreateWithoutUserInput[] | Prisma.orderPayUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutUserInput | Prisma.orderPayCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.orderPayUpsertWithWhereUniqueWithoutUserInput | Prisma.orderPayUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.orderPayCreateManyUserInputEnvelope
  set?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  disconnect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  delete?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  update?: Prisma.orderPayUpdateWithWhereUniqueWithoutUserInput | Prisma.orderPayUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.orderPayUpdateManyWithWhereWithoutUserInput | Prisma.orderPayUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
}

export type orderPayUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput> | Prisma.orderPayCreateWithoutUserInput[] | Prisma.orderPayUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.orderPayCreateOrConnectWithoutUserInput | Prisma.orderPayCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.orderPayUpsertWithWhereUniqueWithoutUserInput | Prisma.orderPayUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.orderPayCreateManyUserInputEnvelope
  set?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  disconnect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  delete?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  connect?: Prisma.orderPayWhereUniqueInput | Prisma.orderPayWhereUniqueInput[]
  update?: Prisma.orderPayUpdateWithWhereUniqueWithoutUserInput | Prisma.orderPayUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.orderPayUpdateManyWithWhereWithoutUserInput | Prisma.orderPayUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
}

export type orderPayCreateWithoutCourseInput = {
  status_pay: $Enums.StatusPay
  user: Prisma.userCreateNestedOneWithoutOrderPayInput
}

export type orderPayUncheckedCreateWithoutCourseInput = {
  id?: number
  userId: number
  status_pay: $Enums.StatusPay
}

export type orderPayCreateOrConnectWithoutCourseInput = {
  where: Prisma.orderPayWhereUniqueInput
  create: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput>
}

export type orderPayCreateManyCourseInputEnvelope = {
  data: Prisma.orderPayCreateManyCourseInput | Prisma.orderPayCreateManyCourseInput[]
  skipDuplicates?: boolean
}

export type orderPayUpsertWithWhereUniqueWithoutCourseInput = {
  where: Prisma.orderPayWhereUniqueInput
  update: Prisma.XOR<Prisma.orderPayUpdateWithoutCourseInput, Prisma.orderPayUncheckedUpdateWithoutCourseInput>
  create: Prisma.XOR<Prisma.orderPayCreateWithoutCourseInput, Prisma.orderPayUncheckedCreateWithoutCourseInput>
}

export type orderPayUpdateWithWhereUniqueWithoutCourseInput = {
  where: Prisma.orderPayWhereUniqueInput
  data: Prisma.XOR<Prisma.orderPayUpdateWithoutCourseInput, Prisma.orderPayUncheckedUpdateWithoutCourseInput>
}

export type orderPayUpdateManyWithWhereWithoutCourseInput = {
  where: Prisma.orderPayScalarWhereInput
  data: Prisma.XOR<Prisma.orderPayUpdateManyMutationInput, Prisma.orderPayUncheckedUpdateManyWithoutCourseInput>
}

export type orderPayScalarWhereInput = {
  AND?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
  OR?: Prisma.orderPayScalarWhereInput[]
  NOT?: Prisma.orderPayScalarWhereInput | Prisma.orderPayScalarWhereInput[]
  id?: Prisma.IntFilter<"orderPay"> | number
  userId?: Prisma.IntFilter<"orderPay"> | number
  courseId?: Prisma.IntFilter<"orderPay"> | number
  status_pay?: Prisma.EnumStatusPayFilter<"orderPay"> | $Enums.StatusPay
}

export type orderPayCreateWithoutUserInput = {
  status_pay: $Enums.StatusPay
  course: Prisma.courseCreateNestedOneWithoutOrderPayInput
}

export type orderPayUncheckedCreateWithoutUserInput = {
  id?: number
  courseId: number
  status_pay: $Enums.StatusPay
}

export type orderPayCreateOrConnectWithoutUserInput = {
  where: Prisma.orderPayWhereUniqueInput
  create: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput>
}

export type orderPayCreateManyUserInputEnvelope = {
  data: Prisma.orderPayCreateManyUserInput | Prisma.orderPayCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type orderPayUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.orderPayWhereUniqueInput
  update: Prisma.XOR<Prisma.orderPayUpdateWithoutUserInput, Prisma.orderPayUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.orderPayCreateWithoutUserInput, Prisma.orderPayUncheckedCreateWithoutUserInput>
}

export type orderPayUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.orderPayWhereUniqueInput
  data: Prisma.XOR<Prisma.orderPayUpdateWithoutUserInput, Prisma.orderPayUncheckedUpdateWithoutUserInput>
}

export type orderPayUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.orderPayScalarWhereInput
  data: Prisma.XOR<Prisma.orderPayUpdateManyMutationInput, Prisma.orderPayUncheckedUpdateManyWithoutUserInput>
}

export type orderPayCreateManyCourseInput = {
  id?: number
  userId: number
  status_pay: $Enums.StatusPay
}

export type orderPayUpdateWithoutCourseInput = {
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
  user?: Prisma.userUpdateOneRequiredWithoutOrderPayNestedInput
}

export type orderPayUncheckedUpdateWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type orderPayUncheckedUpdateManyWithoutCourseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type orderPayCreateManyUserInput = {
  id?: number
  courseId: number
  status_pay: $Enums.StatusPay
}

export type orderPayUpdateWithoutUserInput = {
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
  course?: Prisma.courseUpdateOneRequiredWithoutOrderPayNestedInput
}

export type orderPayUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}

export type orderPayUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  courseId?: Prisma.IntFieldUpdateOperationsInput | number
  status_pay?: Prisma.EnumStatusPayFieldUpdateOperationsInput | $Enums.StatusPay
}



export type orderPaySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  courseId?: boolean
  status_pay?: boolean
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orderPay"]>



export type orderPaySelectScalar = {
  id?: boolean
  userId?: boolean
  courseId?: boolean
  status_pay?: boolean
}

export type orderPayOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "courseId" | "status_pay", ExtArgs["result"]["orderPay"]>
export type orderPayInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.userDefaultArgs<ExtArgs>
  course?: boolean | Prisma.courseDefaultArgs<ExtArgs>
}

export type $orderPayPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orderPay"
  objects: {
    user: Prisma.$userPayload<ExtArgs>
    course: Prisma.$coursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    courseId: number
    status_pay: $Enums.StatusPay
  }, ExtArgs["result"]["orderPay"]>
  composites: {}
}

export type orderPayGetPayload<S extends boolean | null | undefined | orderPayDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$orderPayPayload, S>

export type orderPayCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<orderPayFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrderPayCountAggregateInputType | true
  }

export interface orderPayDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orderPay'], meta: { name: 'orderPay' } }
  /**
   * Find zero or one OrderPay that matches the filter.
   * @param {orderPayFindUniqueArgs} args - Arguments to find a OrderPay
   * @example
   * // Get one OrderPay
   * const orderPay = await prisma.orderPay.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends orderPayFindUniqueArgs>(args: Prisma.SelectSubset<T, orderPayFindUniqueArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrderPay that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {orderPayFindUniqueOrThrowArgs} args - Arguments to find a OrderPay
   * @example
   * // Get one OrderPay
   * const orderPay = await prisma.orderPay.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends orderPayFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, orderPayFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderPay that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayFindFirstArgs} args - Arguments to find a OrderPay
   * @example
   * // Get one OrderPay
   * const orderPay = await prisma.orderPay.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends orderPayFindFirstArgs>(args?: Prisma.SelectSubset<T, orderPayFindFirstArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrderPay that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayFindFirstOrThrowArgs} args - Arguments to find a OrderPay
   * @example
   * // Get one OrderPay
   * const orderPay = await prisma.orderPay.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends orderPayFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, orderPayFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrderPays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrderPays
   * const orderPays = await prisma.orderPay.findMany()
   * 
   * // Get first 10 OrderPays
   * const orderPays = await prisma.orderPay.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderPayWithIdOnly = await prisma.orderPay.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends orderPayFindManyArgs>(args?: Prisma.SelectSubset<T, orderPayFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrderPay.
   * @param {orderPayCreateArgs} args - Arguments to create a OrderPay.
   * @example
   * // Create one OrderPay
   * const OrderPay = await prisma.orderPay.create({
   *   data: {
   *     // ... data to create a OrderPay
   *   }
   * })
   * 
   */
  create<T extends orderPayCreateArgs>(args: Prisma.SelectSubset<T, orderPayCreateArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrderPays.
   * @param {orderPayCreateManyArgs} args - Arguments to create many OrderPays.
   * @example
   * // Create many OrderPays
   * const orderPay = await prisma.orderPay.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends orderPayCreateManyArgs>(args?: Prisma.SelectSubset<T, orderPayCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a OrderPay.
   * @param {orderPayDeleteArgs} args - Arguments to delete one OrderPay.
   * @example
   * // Delete one OrderPay
   * const OrderPay = await prisma.orderPay.delete({
   *   where: {
   *     // ... filter to delete one OrderPay
   *   }
   * })
   * 
   */
  delete<T extends orderPayDeleteArgs>(args: Prisma.SelectSubset<T, orderPayDeleteArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrderPay.
   * @param {orderPayUpdateArgs} args - Arguments to update one OrderPay.
   * @example
   * // Update one OrderPay
   * const orderPay = await prisma.orderPay.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends orderPayUpdateArgs>(args: Prisma.SelectSubset<T, orderPayUpdateArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrderPays.
   * @param {orderPayDeleteManyArgs} args - Arguments to filter OrderPays to delete.
   * @example
   * // Delete a few OrderPays
   * const { count } = await prisma.orderPay.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends orderPayDeleteManyArgs>(args?: Prisma.SelectSubset<T, orderPayDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrderPays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrderPays
   * const orderPay = await prisma.orderPay.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends orderPayUpdateManyArgs>(args: Prisma.SelectSubset<T, orderPayUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one OrderPay.
   * @param {orderPayUpsertArgs} args - Arguments to update or create a OrderPay.
   * @example
   * // Update or create a OrderPay
   * const orderPay = await prisma.orderPay.upsert({
   *   create: {
   *     // ... data to create a OrderPay
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrderPay we want to update
   *   }
   * })
   */
  upsert<T extends orderPayUpsertArgs>(args: Prisma.SelectSubset<T, orderPayUpsertArgs<ExtArgs>>): Prisma.Prisma__orderPayClient<runtime.Types.Result.GetResult<Prisma.$orderPayPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrderPays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayCountArgs} args - Arguments to filter OrderPays to count.
   * @example
   * // Count the number of OrderPays
   * const count = await prisma.orderPay.count({
   *   where: {
   *     // ... the filter for the OrderPays we want to count
   *   }
   * })
  **/
  count<T extends orderPayCountArgs>(
    args?: Prisma.Subset<T, orderPayCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderPayCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrderPay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderPayAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderPayAggregateArgs>(args: Prisma.Subset<T, OrderPayAggregateArgs>): Prisma.PrismaPromise<GetOrderPayAggregateType<T>>

  /**
   * Group by OrderPay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {orderPayGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends orderPayGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: orderPayGroupByArgs['orderBy'] }
      : { orderBy?: orderPayGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, orderPayGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderPayGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orderPay model
 */
readonly fields: orderPayFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orderPay.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__orderPayClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.userDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.userDefaultArgs<ExtArgs>>): Prisma.Prisma__userClient<runtime.Types.Result.GetResult<Prisma.$userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  course<T extends Prisma.courseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.courseDefaultArgs<ExtArgs>>): Prisma.Prisma__courseClient<runtime.Types.Result.GetResult<Prisma.$coursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orderPay model
 */
export interface orderPayFieldRefs {
  readonly id: Prisma.FieldRef<"orderPay", 'Int'>
  readonly userId: Prisma.FieldRef<"orderPay", 'Int'>
  readonly courseId: Prisma.FieldRef<"orderPay", 'Int'>
  readonly status_pay: Prisma.FieldRef<"orderPay", 'StatusPay'>
}
    

// Custom InputTypes
/**
 * orderPay findUnique
 */
export type orderPayFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter, which orderPay to fetch.
   */
  where: Prisma.orderPayWhereUniqueInput
}

/**
 * orderPay findUniqueOrThrow
 */
export type orderPayFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter, which orderPay to fetch.
   */
  where: Prisma.orderPayWhereUniqueInput
}

/**
 * orderPay findFirst
 */
export type orderPayFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter, which orderPay to fetch.
   */
  where?: Prisma.orderPayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orderPays to fetch.
   */
  orderBy?: Prisma.orderPayOrderByWithRelationInput | Prisma.orderPayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orderPays.
   */
  cursor?: Prisma.orderPayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orderPays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orderPays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orderPays.
   */
  distinct?: Prisma.OrderPayScalarFieldEnum | Prisma.OrderPayScalarFieldEnum[]
}

/**
 * orderPay findFirstOrThrow
 */
export type orderPayFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter, which orderPay to fetch.
   */
  where?: Prisma.orderPayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orderPays to fetch.
   */
  orderBy?: Prisma.orderPayOrderByWithRelationInput | Prisma.orderPayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orderPays.
   */
  cursor?: Prisma.orderPayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orderPays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orderPays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orderPays.
   */
  distinct?: Prisma.OrderPayScalarFieldEnum | Prisma.OrderPayScalarFieldEnum[]
}

/**
 * orderPay findMany
 */
export type orderPayFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter, which orderPays to fetch.
   */
  where?: Prisma.orderPayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orderPays to fetch.
   */
  orderBy?: Prisma.orderPayOrderByWithRelationInput | Prisma.orderPayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orderPays.
   */
  cursor?: Prisma.orderPayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orderPays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orderPays.
   */
  skip?: number
  distinct?: Prisma.OrderPayScalarFieldEnum | Prisma.OrderPayScalarFieldEnum[]
}

/**
 * orderPay create
 */
export type orderPayCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * The data needed to create a orderPay.
   */
  data: Prisma.XOR<Prisma.orderPayCreateInput, Prisma.orderPayUncheckedCreateInput>
}

/**
 * orderPay createMany
 */
export type orderPayCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orderPays.
   */
  data: Prisma.orderPayCreateManyInput | Prisma.orderPayCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orderPay update
 */
export type orderPayUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * The data needed to update a orderPay.
   */
  data: Prisma.XOR<Prisma.orderPayUpdateInput, Prisma.orderPayUncheckedUpdateInput>
  /**
   * Choose, which orderPay to update.
   */
  where: Prisma.orderPayWhereUniqueInput
}

/**
 * orderPay updateMany
 */
export type orderPayUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orderPays.
   */
  data: Prisma.XOR<Prisma.orderPayUpdateManyMutationInput, Prisma.orderPayUncheckedUpdateManyInput>
  /**
   * Filter which orderPays to update
   */
  where?: Prisma.orderPayWhereInput
  /**
   * Limit how many orderPays to update.
   */
  limit?: number
}

/**
 * orderPay upsert
 */
export type orderPayUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * The filter to search for the orderPay to update in case it exists.
   */
  where: Prisma.orderPayWhereUniqueInput
  /**
   * In case the orderPay found by the `where` argument doesn't exist, create a new orderPay with this data.
   */
  create: Prisma.XOR<Prisma.orderPayCreateInput, Prisma.orderPayUncheckedCreateInput>
  /**
   * In case the orderPay was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.orderPayUpdateInput, Prisma.orderPayUncheckedUpdateInput>
}

/**
 * orderPay delete
 */
export type orderPayDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
  /**
   * Filter which orderPay to delete.
   */
  where: Prisma.orderPayWhereUniqueInput
}

/**
 * orderPay deleteMany
 */
export type orderPayDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orderPays to delete
   */
  where?: Prisma.orderPayWhereInput
  /**
   * Limit how many orderPays to delete.
   */
  limit?: number
}

/**
 * orderPay without action
 */
export type orderPayDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orderPay
   */
  select?: Prisma.orderPaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the orderPay
   */
  omit?: Prisma.orderPayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.orderPayInclude<ExtArgs> | null
}
